apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetail-ingress
  namespace: kubetail-system
spec:
  rules:
  - host: kubetail.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubetail-dashboard
            port:
              name: http